[package]

name = "control-rust"
version = "0.0.1"
authors = ["Brandon Skari <brandon@skari.org>"]

[dependencies]
chrono = ">=0.4.6"
enum_primitive = ">=0.1.1"
getopts = ">=0.2.18"
libc = ">=0.2.43"
log = ">=0.4.5"
num = ">=0.2.0"
simplelog = ">=0.5.2"
